import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from '@react-pdf/renderer'

// Register fonts (optional, can use default fonts)
Font.register({
  family: 'Helvetica',
  fonts: [
    { src: 'https://cdn.jsdelivr.net/npm/@react-pdf/font/lib/fonts/Helvetica.ttf', fontWeight: 'normal' },
    { src: 'https://cdn.jsdelivr.net/npm/@react-pdf/font/lib/fonts/Helvetica-Bold.ttf', fontWeight: 'bold' },
  ],
})

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #000',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#10b981',
  },
  content: {
    fontSize: 12,
    lineHeight: 1.5,
  },
  table: {
    display: 'table',
    width: 'auto',
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
  },
  tableCol: {
    width: '25%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
  },
  tableCell: {
    margin: 5,
    fontSize: 10,
  },
  tableHeader: {
    backgroundColor: '#10b981',
    color: '#fff',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#666',
    borderTop: '1 solid #000',
    paddingTop: 10,
  },
})

interface PDFDocumentProps {
  title: string
  subtitle: string
  content: string
  data?: any[]
  generatedBy: string
  generatedAt: string
}

export const PDFDocument = ({ title, subtitle, content, data, generatedBy, generatedAt }: PDFDocumentProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>{subtitle}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Overview</Text>
        <Text style={styles.content}>{content}</Text>
      </View>

      {data && data.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Data Summary</Text>
          <View style={styles.table}>
            <View style={styles.tableRow}>
              {Object.keys(data[0]).map((key, index) => (
                <View key={index} style={[styles.tableCol, styles.tableHeader]}>
                  <Text style={styles.tableCell}>{key.toUpperCase()}</Text>
                </View>
              ))}
            </View>
            {data.map((row, rowIndex) => (
              <View key={rowIndex} style={styles.tableRow}>
                {Object.values(row).map((value: any, colIndex) => (
                  <View key={colIndex} style={styles.tableCol}>
                    <Text style={styles.tableCell}>{String(value)}</Text>
                  </View>
                ))}
              </View>
            ))}
          </View>
        </View>
      )}

      <View style={styles.footer}>
        <Text>Generated by {generatedBy} on {generatedAt}</Text>
        <Text>LUMINA OS Enterprise - Confidential</Text>
      </View>
    </Page>
  </Document>
)

interface PDFDownloadButtonProps {
  fileName: string
  documentProps: PDFDocumentProps
  label?: string
}

export const PDFDownloadButton = ({ fileName, documentProps, label = 'Download PDF' }: PDFDownloadButtonProps) => (
  <PDFDownloadLink document={<PDFDocument {...documentProps} />} fileName={fileName}>
    {({ loading }) => (
      <button
        disabled={loading}
        className="px-4 py-2 bg-emerald-500 text-black rounded-lg hover:bg-emerald-400 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {loading ? 'Generating PDF...' : label}
      </button>
    )}
  </PDFDownloadLink>
)

// Helper function to generate PDF document props
export const generatePDFProps = (
  title: string,
  subtitle: string,
  content: string,
  data?: any[]
): PDFDocumentProps => ({
  title,
  subtitle,
  content,
  data,
  generatedBy: 'LUMINA OS Enterprise',
  generatedAt: new Date().toLocaleString('id-ID'),
})
